package com.tpstreams.player.util

import android.net.Uri
import android.util.Log
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import androidx.media3.common.MimeTypes
import androidx.media3.common.util.UnstableApi
import com.tpstreams.player.data.AssetInfo

@UnstableApi
object MediaItemUtils {
    private const val TAG = "MediaItemUtils"

    data class MediaItemResult(
        val mediaItem: MediaItem,
        val subtitleMetadata: Map<String, Boolean>
    )

    fun buildMediaItem(
        assetInfo: AssetInfo,
        title: String,
        orgId: String,
        assetId: String,
        accessToken: String
    ): MediaItemResult {
        val subtitleConfigurations = mutableListOf<MediaItem.SubtitleConfiguration>()
        val subtitleMetadata = mutableMapOf<String, Boolean>()
        
        if (assetInfo.videoObj != null && assetInfo.videoObj.has("tracks")) {
            val tracks = assetInfo.videoObj.getJSONArray("tracks")
            for (i in 0 until tracks.length()) {
                val track = tracks.getJSONObject(i)
                if (track.getString("type") == "Subtitle") {
                    val language = track.getString("language")
                    val url = track.getString("url")
                    val isAutoGenerated = track.has("subtitle_type") && 
                        track.getString("subtitle_type") == "Auto Generated"
                    
                    val name = if (track.has("name") && !track.getString("name").isNullOrEmpty()) {
                        track.getString("name")
                    } else {
                        language.replaceFirstChar { it.uppercase() }
                    }
                    
                    subtitleMetadata[language] = isAutoGenerated
                    
                    try {
                        val subtitleConfig = MediaItem.SubtitleConfiguration.Builder(Uri.parse(url))
                            .setLanguage(language)
                            .setLabel(name)
                            .setMimeType(MimeTypes.TEXT_VTT)
                            .build()
                        
                        subtitleConfigurations.add(subtitleConfig)
                    } catch (e: Exception) {
                        Log.e(TAG, "Error adding subtitle track: ${e.message}", e)
                    }
                }
            }
        }

        val mediaItem = MediaItem.Builder()
            .setUri(assetInfo.mediaUrl)
            .setMediaId(assetId)
            .apply {
                val metadata = MediaMetadata.Builder()
                    .setTitle(title)
                    .setArtworkUri(if (assetInfo.thumbnailUrl.isNotEmpty()) Uri.parse(assetInfo.thumbnailUrl) else null)
                    .build()
                setMediaMetadata(metadata)
                
                if (assetInfo.enableDrm) {
                    val licenseUrl = "https://app.tpstreams.com/api/v1/$orgId/assets/$assetId/drm_license/?access_token=$accessToken"
                    val drmHeaders = mapOf("Authorization" to "Bearer $accessToken")
                    
                    val drmConfig = MediaItem.DrmConfiguration.Builder(C.WIDEVINE_UUID)
                        .setLicenseUri(licenseUrl)
                        .setLicenseRequestHeaders(drmHeaders)
                        .setMultiSession(true)
                        .build()
                    
                    setDrmConfiguration(drmConfig)
                }
                
                if (subtitleConfigurations.isNotEmpty()) {
                    setSubtitleConfigurations(subtitleConfigurations)
                }
            }
            .build()
            
        return MediaItemResult(mediaItem, subtitleMetadata)
    }
}
