package com.tpstreams.player.util

import android.net.Uri
import android.util.Log
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import androidx.media3.common.MimeTypes
import androidx.media3.common.util.UnstableApi
import com.tpstreams.player.TPStreamsSDK
import com.tpstreams.player.data.network.model.AssetInfo

@UnstableApi
object MediaItemUtils {
    private const val TAG = "MediaItemUtils"

    data class MediaItemResult(
        val mediaItem: MediaItem,
        val subtitleMetadata: Map<String, Boolean>,
        val drmLicenseUrl: String? = null
    )

    fun buildMediaItem(
        assetInfo: AssetInfo,
        title: String,
        orgId: String,
        assetId: String,
        accessToken: String
    ): MediaItemResult {
        val subtitleConfigurations = mutableListOf<MediaItem.SubtitleConfiguration>()
        val subtitleMetadata = mutableMapOf<String, Boolean>()
        
        if (assetInfo.videoObj != null && assetInfo.videoObj.has("tracks")) {
            val tracks = assetInfo.videoObj.getJSONArray("tracks")
            for (i in 0 until tracks.length()) {
                val track = tracks.getJSONObject(i)
                if (track.getString("type") == "Subtitle") {
                    val language = track.getString("language")
                    val url = track.getString("url")
                    val isAutoGenerated = track.has("subtitle_type") && 
                        track.getString("subtitle_type") == "Auto Generated"
                    
                    val name = if (track.has("name") && !track.getString("name").isNullOrEmpty()) {
                        track.getString("name")
                    } else {
                        language.replaceFirstChar { it.uppercase() }
                    }
                    
                    subtitleMetadata[language] = isAutoGenerated
                    
                    try {
                        val subtitleConfig = MediaItem.SubtitleConfiguration.Builder(Uri.parse(url))
                            .setLanguage(language)
                            .setLabel(name)
                            .setMimeType(MimeTypes.TEXT_VTT)
                            .build()
                        
                        subtitleConfigurations.add(subtitleConfig)
                    } catch (e: Exception) {
                        Log.e(TAG, "Error adding subtitle track: ${e.message}", e)
                    }
                }
            }
        }

        val playbackUri = buildPlaybackUri(assetInfo.mediaUrl, assetInfo.isAes, accessToken)

        val metadata = MediaMetadata.Builder()
            .setTitle(title)
            .setArtworkUri(if (assetInfo.thumbnailUrl.isNotEmpty()) Uri.parse(assetInfo.thumbnailUrl) else null)
            .build()

        val builder = MediaItem.Builder()
            .setUri(playbackUri)
            .setMediaId(assetId)
            .setMediaMetadata(metadata)

        val drmLicenseUrl: String?
        if (assetInfo.enableDrm) {
            val apiService = TPStreamsSDK.apiService
            val licenseUrl = apiService.drmLicenseUrl(orgId, assetId, accessToken)
            drmLicenseUrl = licenseUrl

            val drmConfigBuilder = MediaItem.DrmConfiguration.Builder(C.WIDEVINE_UUID)
                .setLicenseUri(licenseUrl)
                .setMultiSession(true)

            val authHeaders = TPStreamsSDK.getAuthHeaders()
            if (authHeaders.isNotEmpty()) {
                drmConfigBuilder.setLicenseRequestHeaders(authHeaders)
            }
            builder.setDrmConfiguration(drmConfigBuilder.build())
        } else {
            drmLicenseUrl = null
        }

        if (subtitleConfigurations.isNotEmpty()) {
            builder.setSubtitleConfigurations(subtitleConfigurations)
        }

        val mediaItem = builder.build()
            
        return MediaItemResult(mediaItem, subtitleMetadata, drmLicenseUrl)
    }

    private fun buildPlaybackUri(mediaUrl: String, isAes: Boolean, accessToken: String): Uri {
        val baseUri = Uri.parse(mediaUrl)
        if (!isAes || accessToken.isBlank()) return baseUri
        return baseUri.buildUpon()
            .appendQueryParameter("tp_token", accessToken)
            .build()
    }
}
