package com.tpstreams.player.tracks

import android.util.Log
import androidx.annotation.OptIn
import androidx.media3.common.C
import androidx.media3.common.MimeTypes
import androidx.media3.common.util.UnstableApi
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.exoplayer.trackselection.DefaultTrackSelector

/**
 * Manages subtitle and caption track selection and metadata for a player instance.
 */
@OptIn(UnstableApi::class)
internal class TextTrackManager(
    private val exoPlayer: ExoPlayer,
    private val trackSelector: DefaultTrackSelector,
) {

    private var subtitleMetadata: Map<String, Boolean> = emptyMap()

    fun updateSubtitleMetadata(metadata: Map<String, Boolean>) {
        subtitleMetadata = metadata
    }

    fun getAvailableTextTracks(): List<Pair<String, String>> {
        val tracks = mutableListOf<Pair<String, String>>()

        for (group in exoPlayer.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_TEXT) continue
            for (i in 0 until group.length) {
                if (!group.isTrackSupported(i)) continue
                val format = group.getTrackFormat(i)
                if (format.sampleMimeType == MimeTypes.APPLICATION_CEA608) continue
                val language = format.language ?: "unknown"
                val label = format.label ?: language
                tracks.add(language to label)
            }
        }

        return tracks
    }

    fun setTextTrackByLanguage(language: String?) {
        val parametersBuilder = trackSelector.buildUponParameters()

        if (language == null) {
            parametersBuilder.setPreferredTextLanguage(null)
            parametersBuilder.setSelectUndeterminedTextLanguage(false)
            Log.d(TAG, "Disabling text tracks")
        } else {
            parametersBuilder.setPreferredTextLanguage(language)
            parametersBuilder.setSelectUndeterminedTextLanguage(true)
            parametersBuilder.setDisabledTextTrackSelectionFlags(0)
            Log.d(TAG, "Setting preferred text language to: $language")
        }

        trackSelector.parameters = parametersBuilder.build()

        val currentPosition = exoPlayer.currentPosition
        if (exoPlayer.isPlaying) {
            exoPlayer.seekTo(currentPosition)
        }
    }

    fun getActiveTextTrack(): Pair<String, String>? {
        for (group in exoPlayer.currentTracks.groups) {
            if (group.type != C.TRACK_TYPE_TEXT) continue
            for (i in 0 until group.length) {
                if (!group.isTrackSelected(i)) continue
                val format = group.getTrackFormat(i)
                val language = format.language ?: "unknown"
                val label = format.label ?: language
                return language to label
            }
        }
        return null
    }

    fun isSubtitleAutoGenerated(language: String): Boolean = subtitleMetadata[language] ?: false

    fun enableDefaultCaptions() {
        val defaultTrack = getAvailableTextTracks().firstOrNull() ?: return
        setTextTrackByLanguage(defaultTrack.first)
    }

    private companion object {
        private const val TAG = "TextTrackManager"
    }
}
